### ISSUE TITLE
Plugin need restarting QGIS to work

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-milstd2525-plugin#2]
After installation, QGIS need to be restarted so that the renderer gets active. Otherwise a warning saying that the renderer does not have a GUI.

**Comment by SrNetoChan** [comment]
@volaya I tried to replicate this on QGIS 3. Although I was not able to replicate the "renderer does not have a GUI" error, nevertheless other issues appeared from fresh install and disabling/enabling the plugin without rebooting QGIS:

1. Enabling and disabling the plugin won't update the Styling panel rendering options. One needs to open a layer's properties for it to update the MIL2525 renderer option on the Styling Panel. (If you disable, the renderer still shows in the list, if you enable the renderer won't show)

2. When using the SDIC code widget in a layer, if you disable the plugin, an error will show on the feature form. Even if you enable back the plugin this still happens.**You need to reboot.**

![image](https://user-images.githubusercontent.com/3607161/43314744-c8fb2fbe-918b-11e8-99b1-8e3311b5a1b0.png)

**Comment by SrNetoChan** [comment]
@volaya is this a won't fix as well?

**Comment by volaya** [comment]
I dont see how we can solve the issue due to enabling/disabling the panel. It should be QGIS wo informs the style panel that there are new renderers, so it's a core issue, not a plugin one, i think.

For the moment, we can document that, telling the users that the plugin should be active when starting the session, and it should remain like that

**Comment by SrNetoChan** [comment]
@volaya Just checked, it's already documented. Closing this one as well.
